modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="cm"
version="1.0.0"
displayName="ChickenMOD"
credits="RLJR - CmMcMOD"
displayURL="https://github.com/Wey2shop/cmMcMOD"
authors="RLJR"

[[dependencies.cm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




